indir: .../lama/test-image # to be overriden in CLI   #设置为自己的
outdir: .../lama/out-put # to be overriden in CLI

model:
  path: .../lama/big-lama/ # to be overriden in CLI
  checkpoint: .../lama/big-lama/models/best.ckpt

dataset:
  kind: default
  img_suffix: .jpg
  pad_out_to_modulo: 8

device: cuda
out_key: inpainted

refine: False # refiner will only run if this is True
refiner:
  gpu_ids: "0," # the GPU ids of the machine to use. If only single GPU, use: "0,"
  modulo: ${dataset.pad_out_to_modulo}
  n_iters: 10 # number of iterations of refinement for each scale
  lr: 0.002 # learning rate
  min_side: 512 # all sides of image on all scales should be >= min_side / sqrt(2)
  max_scales: 3 # max number of downscaling scales for the image-mask pyramid
  px_budget: 1800000 # pixels budget. Any image will be resized to satisfy height*width <= px_budget